version: '3'

networks:
  vpcbr:
    ipam:
     config:
       - subnet: 10.5.0.0/16


services:
  client:
    container_name: client
    image: client
    depends_on:
     - server
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  server:
    container_name: server
    image: server
    ports:
     - "5555:5555"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6


