version: '3'


services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: DockerFile_client
    depends_on:
     - server


  server:
    container_name: server
    build:
      context: .
      dockerfile: DockerFile
    ports:
     - "5555:5555"


